# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyNetflix' do
  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!
  use_modular_headers!
  # Pods for MyNetflix
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Kingfisher', '~> 5.0'
end
