# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todo

  pod 'Amplify'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'

end
