# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmployeeManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmployeeManagement
  pod 'Alamofire', '~> 5.0.0-rc.1'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SWRevealViewController', '~> 2.3'
  pod 'FSCalendar'

end
